# This is a template for other packages (i.e., beside pfs_pipe2d) to use
# as a ".travis.yml" file to enable Travis-CI. This enables CI on the
# entire pipeline when changing only a single product in the stack.

language: python  # Not really, because we're running Docker, but we need something
services:
  - docker
sudo: true
python:
  - 3.6
os:
  - linux
matrix:
  fast_finish: true
notifications:
  email: false
  slack:
    secure: hMnFmfbfVhJIhrIcPZjDY3A/6nOYkewGLu6hnViQ3AGAUfGhMdHnsHpglWGkQiGZvytI5VoukJjrOBdxt2VA0pdsXPzV2XIsshS75eKwfwW0z5KT1cPoFTmkIxoK1Bhrs/k0bBjUU6J6Efya25Ub4m6JBk4MNW8g+T+RL0fRmzpImQEXavQgvEHWm2fHjyr0eGPdXdqXJLuvhHJvyXBrMBJoqUQZ1+IvVeAMFdYMswJe401o65+0izDzfr8+3N4QwtP680vzIyhxrghq9/vNAO222I1nM/ScNV6b5lSjYbtfq2MNOHKI6mOBquAY+amwh+Z0dT3Ywqr0jJ0f01yUgJXKEn3eyljKdgLxDPJ/t6OIW0KjuD800JkyhaRYdup9K3p8O8ii6eRAEqzoUKEw45NdnmFYBtV+oV5t8UxSZ6UbiXmhs4R3kGd5ql5cQDbZAES7Hb5FG/0O2fVdltm8M81GU41KjjTfsx+Nf1LBOaeVkevtpduLuKWao1y7LBu/fMle4Xr9O1IE66DFegVORbkCRebD9Ej1264zhAaIddhzehy+Ivi1wzgm0fU8s+IwwmOh2UNqOgyfDBBXWUUH6f7+EO96TTApb7wMVItKiWRJr4sYSAYodOhhiXzSdTdoIxg7IsrmdPl2v358p/W7KTOSlt8eOMK+tnFVMbWpZn8=
branches:
  only:
    - master

# The actual installation is done under the 'script' so as to consolidate the
# necessary front-end machinery (intercept log, decide which branch to use).
install:
  - cd $HOME
  - git clone -b ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} --single-branch http://github.com/Subaru-PFS/pfs_pipe2d || git clone -b master --single-branch http://github.com/Subaru-PFS/pfs_pipe2d
script: /bin/bash pfs_pipe2d/bin/pfs_travis.sh
